### ISSUE TITLE
Addressing messages with /me

### ISSUE THREAD

**Issue by ForNeVeR** [ermine/sulci#4]
```
<xxx> sulci: кофе не выпила ещё с утра?
<sulci> а надо тут скобки нужно менять. Ещё немножко, но /me сегодня по вкусу
```

I think that the last message should be `xxx: а надо тут скобки нужно менять. Ещё немножко, но /me сегодня по вкусу`.

It seems that sulci will not use addressing (such as `xxx:`) if the message contains `/me` in any place. It should detect only `/me` at the message start instead.

**Comment by ermine** [comment]
On Sun, Nov 15, 2015 at 09:34:43PM -0800, Friedrich von Never wrote:
> ```
> <xxx> sulci: кофе не выпила ещё с утра?
> <sulci> а надо тут скобки нужно менять. Ещё немножко, но /me сегодня по вкусу
> ```
> 
> I think that the last message should be `xxx: а надо тут скобки нужно менять. Ещё немножко, но /me сегодня по вкусу`.
> 
> It seems that sulci will not use addressing (such as `xxx:`) if the message contains `/me` in any place. It should detect only `/me` at the message start instead.

It wont address if "/me" is first word in that generated sentence.
Shown behaviour is not expected, there are twro possible explantations:
1) Your's client bug
2) Sulci's bug, but i never saw that behaviour.

ermine
